### ISSUE TITLE
MacOS Saving Problem

### ISSUE THREAD

**Issue by periloustxt** [robertkist/ditherista#1]
When trying to save an image, MacOS Ventura asks for permission for Ditherista to access 'Home', 'Downloads', 'Desktop', or any filesystem folder each time a save is attempted.

I have tried going into system settings in MacOS, Privacy & Security settings, and selected Files and Folders > Ditherista > and each setting for those folders are enabled, but the problem persists.

**Comment by robertkist** [comment]
I managed to replicate the behavior. It seems to be related to the File dialog - I'll try compiling with a newer Qt version and see if that helps.

Workaround: dragging from Ditherista to the e.g. the Desktop or Documents doesn't trigger this warning.

**Comment by periloustxt** [comment]
fwiw i am so grateful for this software and thank you for your time! didn't think to drag--will use this until a new release is rolled out!

**Comment by robertkist** [comment]
It seems building with the latest Qt version 6.6.1 solves the problem.
Please find a new build here: https://github.com/robertkist/ditherista/releases/tag/2023-05-12b
Let me know if this fixes the problem :)

**Comment by periloustxt** [comment]
This looks to have worked! Loving it! Thank you.
